  

    # Step 1: Uninstall requests package installed via rpm (this will fix the conflict)
    - name: Uninstall requests package installed via rpm
      dnf:
        name: python3-requests
        state: absent
      become: true

    # Step 2: Install required dependencies
    - name: Install dependencies
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    # Step 3: Add Docker repository
    - name: Add Docker repository
      copy:
        dest: /etc/yum.repos.d/docker-ce.repo
        content: |
          [docker-ce-stable]
          name=Docker CE Stable - $basearch
          baseurl=https://download.docker.com/linux/centos/7/$basearch/stable
          enabled=1
          gpgcheck=1
          gpgkey=https://download.docker.com/linux/centos/gpg
        mode: '0644'

    # Step 4: Install Docker CE
    - name: Install Docker
      dnf:
        name: docker-ce
        state: present

    # Step 5: Start Docker service
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    # Step 6: Install Docker Compose
    - name: Install Docker Compose
      shell: |
        curl -L https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    # Step 7: Verify Docker Compose installation
    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    # Step 8: Show Docker Compose version
    - name: Show Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
# intall pip3 and docker sdk for python
    - name: Install pip3 on Amazon Linux
      dnf:
        name: python3-pip
        state: present


    # Step 9: Install Docker SDK for Python
    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
        extra_args: --no-deps
        
    - name: Install requests library
      ansible.builtin.pip:
        name: requests
        state: present
        #mudei
        # Step 10: Add ec2-user to docker group
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    # Step 11: Restart Docker service (to apply group change)
    - name: Restart Docker service to apply group changes
      systemd:
        name: docker
        state: restarted

   

