---
- name: copy docker-compose to remote host
  copy:
    src: "deploy_stack/defaults/docker-compose.yml"
    dest: "/opt/docker-compose.yml"
    
- name: Ensure jsondiff is installed
  pip:
    name: jsondiff
    state: present

- name: deploy stack
  docker_stack:
    state: present
    name: "app"
    compose:
       - "/opt/docker-compose.yml"
    

