---
- name: Check if node is already in swarm
  command: docker info
  register: docker_info
  changed_when: false

- name: Leave swarm if already part of one
  command: docker swarm leave --force
  when: "'Swarm: active' in docker_info.stdout"

  # mudei aqui
- name: Init docker swarm
  docker_swarm:
    state: present
  register: init_swarm
    
- name: join
  set_fact:
    join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"
# aqui
- name: Set join token for workers
  add_host:
    name: "workers"
    join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"