---
- name: Install nginx, Node.js, and npm
  dnf:
    name:
      - nginx
      - nodejs
      - npm
    state: present
    update_cache: yes


- name: Start nginx
  service:
    name: nginx
    state: started

- name: create dir /app
  file: 
    path: /app
    state: directory

- name: copy package.json
  copy:
    src: package.json
    dest: /app/package.json

- name: npm install
  npm:
    path: /app
    state: present

- name: copy index.js
  template:
    src: index.js.j2
    dest: /app/index.js

- name: copy app.service
  copy:
    src: app.service
    dest: /etc/systemd/system/app.service

  
- name: enable app.service
  systemd:
      name: app.service
      enabled: yes

- name: run app.service
  systemd:
      name: app
      state: started


- name: create nginx directories
  file:
    path: "/etc/nginx/sites-available"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: reload nginx

- name: Check NGINX configuration on all machines
  command: nginx -t
  register: nginx_test
  ignore_errors: true

- name: Show NGINX test result
  debug:
    var: nginx_test.stdout_lines

- name: Get NGINX status
  command: systemctl status nginx
  register: nginx_status
  ignore_errors: true

- name: Show NGINX status
  debug:
    var: nginx_status.stdout_lines